import { Container, Spacer } from '@nextui-org/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { ReactNode } from 'react';
import NavBar from './NavBar';

type PageLayoutProps = {
  children: ReactNode;
  title: string;
};

function PageLayout({ children, title }: PageLayoutProps) {
  const router = useRouter();
  const showHeader = router.pathname !== '/login';

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {showHeader && (
        <header>
          <Container lg>
            <NavBar />
          </Container>
        </header>
      )}
      <Spacer y={2} />
      <Container md>
        <main>{children}</main>
      </Container>
    </>
  );
}

export default PageLayout;
