import Head from 'next/head';
import { Inter } from '@next/font/google';
import { signOut } from 'next-auth/react';
import { Button } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Button color='success' onClick={() => signOut()}>
          Log Out
        </Button>
      </main>
    </>
  );
}

